# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: water.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'water.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bwater.proto\x12\x05water\"\xfe\x04\n\x0fWaterSensorData\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x11\n\ttimestamp\x18\x02 \x01(\t\x12\x14\n\x0cinflow_rate2\x18\x03 \x01(\x01\x12\x12\n\ninflow_cod\x18\x04 \x01(\x01\x12\x12\n\ninflow_nh3\x18\x05 \x01(\x01\x12\x13\n\x0boutflow_cod\x18\x06 \x01(\x01\x12\x13\n\x0boutflow_nh3\x18\x07 \x01(\x01\x12%\n\x1d\x62io2_front_aeration_flow_meas\x18\x08 \x01(\x01\x12%\n\x1d\x62io2_front_valve_opening_meas\x18\t \x01(\x01\x12#\n\x1b\x62io2_end_aeration_flow_meas\x18\n \x01(\x01\x12#\n\x1b\x62io2_end_valve_opening_meas\x18\x0b \x01(\x01\x12\x1a\n\x12\x62io2_front_do_meas\x18\x0c \x01(\x01\x12\x18\n\x10\x62io2_end_do_meas\x18\r \x01(\x01\x12\x16\n\x0e\x62io2_mlss_meas\x18\x0e \x01(\x01\x12(\n bio2_aeration_pipe_pressure_meas\x18\x0f \x01(\x01\x12\"\n\x1a\x62io2_1_blower_opening_meas\x18\x10 \x01(\x01\x12 \n\x18\x62io2_1_blower_is_running\x18\x11 \x01(\x05\x12#\n\x1b\x62io2_1_blower_pressure_meas\x18\x12 \x01(\x01\x12\"\n\x1a\x62io2_2_blower_opening_meas\x18\x13 \x01(\x01\x12 \n\x18\x62io2_2_blower_is_running\x18\x14 \x01(\x05\x12#\n\x1b\x62io2_2_blower_pressure_meas\x18\x15 \x01(\x01\"9\n\x0cTrainRequest\x12)\n\tdata_list\x18\x01 \x03(\x0b\x32\x16.water.WaterSensorData\"1\n\rTrainResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2G\n\x11WaterTrainService\x12\x32\n\x05Train\x12\x13.water.TrainRequest\x1a\x14.water.TrainResponseB\x1e\n\tcom.waterB\x0fWaterOuterClassP\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'water_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\tcom.waterB\017WaterOuterClassP\000'
  _globals['_WATERSENSORDATA']._serialized_start=23
  _globals['_WATERSENSORDATA']._serialized_end=661
  _globals['_TRAINREQUEST']._serialized_start=663
  _globals['_TRAINREQUEST']._serialized_end=720
  _globals['_TRAINRESPONSE']._serialized_start=722
  _globals['_TRAINRESPONSE']._serialized_end=771
  _globals['_WATERTRAINSERVICE']._serialized_start=773
  _globals['_WATERTRAINSERVICE']._serialized_end=844
# @@protoc_insertion_point(module_scope)
