# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import water_pb2 as water__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in water_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WaterTrainServiceStub(object):
    """训练服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Train = channel.unary_unary(
                '/water.WaterTrainService/Train',
                request_serializer=water__pb2.TrainRequest.SerializeToString,
                response_deserializer=water__pb2.TrainResponse.FromString,
                _registered_method=True)


class WaterTrainServiceServicer(object):
    """训练服务
    """

    def Train(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WaterTrainServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Train': grpc.unary_unary_rpc_method_handler(
                    servicer.Train,
                    request_deserializer=water__pb2.TrainRequest.FromString,
                    response_serializer=water__pb2.TrainResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'water.WaterTrainService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('water.WaterTrainService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WaterTrainService(object):
    """训练服务
    """

    @staticmethod
    def Train(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/water.WaterTrainService/Train',
            water__pb2.TrainRequest.SerializeToString,
            water__pb2.TrainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WaterModelServiceStub(object):
    """模型管理服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DownloadModel = channel.unary_unary(
                '/water.WaterModelService/DownloadModel',
                request_serializer=water__pb2.ModelDownloadRequest.SerializeToString,
                response_deserializer=water__pb2.ModelDownloadResponse.FromString,
                _registered_method=True)
        self.UploadModel = channel.unary_unary(
                '/water.WaterModelService/UploadModel',
                request_serializer=water__pb2.ModelUploadRequest.SerializeToString,
                response_deserializer=water__pb2.ModelUploadResponse.FromString,
                _registered_method=True)


class WaterModelServiceServicer(object):
    """模型管理服务
    """

    def DownloadModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WaterModelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DownloadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadModel,
                    request_deserializer=water__pb2.ModelDownloadRequest.FromString,
                    response_serializer=water__pb2.ModelDownloadResponse.SerializeToString,
            ),
            'UploadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadModel,
                    request_deserializer=water__pb2.ModelUploadRequest.FromString,
                    response_serializer=water__pb2.ModelUploadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'water.WaterModelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('water.WaterModelService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WaterModelService(object):
    """模型管理服务
    """

    @staticmethod
    def DownloadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/water.WaterModelService/DownloadModel',
            water__pb2.ModelDownloadRequest.SerializeToString,
            water__pb2.ModelDownloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/water.WaterModelService/UploadModel',
            water__pb2.ModelUploadRequest.SerializeToString,
            water__pb2.ModelUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WaterCsvFileServiceStub(object):
    """CSV文件服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadCsvFile = channel.unary_unary(
                '/water.WaterCsvFileService/UploadCsvFile',
                request_serializer=water__pb2.CsvFileUploadRequest.SerializeToString,
                response_deserializer=water__pb2.CsvFileUploadResponse.FromString,
                _registered_method=True)


class WaterCsvFileServiceServicer(object):
    """CSV文件服务
    """

    def UploadCsvFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WaterCsvFileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadCsvFile': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadCsvFile,
                    request_deserializer=water__pb2.CsvFileUploadRequest.FromString,
                    response_serializer=water__pb2.CsvFileUploadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'water.WaterCsvFileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('water.WaterCsvFileService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WaterCsvFileService(object):
    """CSV文件服务
    """

    @staticmethod
    def UploadCsvFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/water.WaterCsvFileService/UploadCsvFile',
            water__pb2.CsvFileUploadRequest.SerializeToString,
            water__pb2.CsvFileUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WaterInstanceMonitorServiceStub(object):
    """实例监控服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MonitorInstances = channel.unary_stream(
                '/water.WaterInstanceMonitorService/MonitorInstances',
                request_serializer=water__pb2.InstanceMonitorRequest.SerializeToString,
                response_deserializer=water__pb2.InstanceMonitorStreamResponse.FromString,
                _registered_method=True)


class WaterInstanceMonitorServiceServicer(object):
    """实例监控服务
    """

    def MonitorInstances(self, request, context):
        """流式推送实例监控数据
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WaterInstanceMonitorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MonitorInstances': grpc.unary_stream_rpc_method_handler(
                    servicer.MonitorInstances,
                    request_deserializer=water__pb2.InstanceMonitorRequest.FromString,
                    response_serializer=water__pb2.InstanceMonitorStreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'water.WaterInstanceMonitorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('water.WaterInstanceMonitorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WaterInstanceMonitorService(object):
    """实例监控服务
    """

    @staticmethod
    def MonitorInstances(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/water.WaterInstanceMonitorService/MonitorInstances',
            water__pb2.InstanceMonitorRequest.SerializeToString,
            water__pb2.InstanceMonitorStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
